version: "3.9"

services:
  db:
    image: postgres:15.2
    volumes:
      - ./tmp/db:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=user_storage
      - POSTGRES_USER=user_storage
      - POSTGRES_PASSWORD=user_storage
    ports:
      - "5432:5432"